import React, { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Battery, ClipboardList, Fuel, Lightbulb, Pencil, Plus, Trash2, Zap } from 'lucide-react'
import { createDefaultEnergySystem, deviceCategories, devicePriorities, energyLabels, fuelSourceTypes, powerSourceTypes } from '../data/energyDefaults.js'
import { evaluateEnergyPlan } from '../utils/energyCalculations.js'
import { getEnergySystemSummary, loadEnergySystemData, saveEnergySystemData } from '../utils/energyStorage.js'
import CollapsibleSection from './CollapsibleSection.jsx'

const emptyDevice = { name: '', category: 'lighting', watts: '', hoursPerDay: '', priority: 'medium', essential: false, notes: '' }
const emptyPower = { name: '', type: 'powerBank', capacityWh: '', usablePercent: 85, maxOutputWatts: '', rechargeable: true, dependsOnGrid: false, solarRecharge: false, notes: '' }
const emptyFuel = { name: '', type: 'butane', amount: '', unit: '罐', usesPerUnit: '', cookingUsesAvailable: '', safeIndoorUse: false, notes: '' }
const emptyPlan = { name: '', durationDays: 3, lightingWhPerDay: '', communicationWhPerDay: '', medicalWhPerDay: '', refrigerationWhPerDay: '', otherWhPerDay: '', cookingUsesPerDay: 1, notes: '' }
const profileLabels = { blackout: '停電模式', conservation: '節能模式', normal: '一般模式' }
const uid = () => `${Date.now()}-${Math.random().toString(36).slice(2,8)}`
const safe = (value) => Number.isFinite(Number(value)) && Number(value) > 0 ? Number(value) : 0
const fmt = (value) => Number(safe(value).toFixed(1)).toString()

function Field({ label, children }) { return <label className="block text-sm font-bold text-soil/75"><span className="mb-1 block">{label}</span>{children}</label> }
function Input({ value, onChange, type='text', ...props }) { return <input className="w-full rounded-xl border border-soil/20 bg-white/70 px-3 py-2" type={type} value={value ?? ''} onChange={(event)=>onChange(event.target.value)} {...props}/> }
function Check({ label, checked, onChange }) { return <label className="flex items-center gap-2 rounded-xl border border-soil/15 bg-white/55 px-3 py-2 text-sm font-bold"><input type="checkbox" checked={checked===true} onChange={(event)=>onChange(event.target.checked)}/>{label}</label> }
function Metric({ label, value, hint }) { return <article className="rounded-2xl border border-soil/15 bg-white/60 p-4"><p className="text-xs font-black text-soil/55">{label}</p><strong className="mt-1 block text-2xl text-[#24483a]">{value}</strong>{hint&&<p className="mt-1 text-xs text-soil/60">{hint}</p>}</article> }
function Title({ icon: Icon, children }) { return <div className="muji-section-title">{Icon&&<Icon size={18}/>}<span>{children}</span></div> }

function DeviceForm({ value, setValue, save, cancel }) { return <form className="energy-form" onSubmit={save}><div className="energy-form-grid"><Field label="名稱"><Input value={value.name} onChange={(v)=>setValue({...value,name:v})}/></Field><Field label="類別"><select value={value.category} onChange={(e)=>setValue({...value,category:e.target.value})}>{deviceCategories.map((v)=><option key={v} value={v}>{energyLabels[v]}</option>)}</select></Field><Field label="瓦數 W"><Input type="number" min="0" step="0.1" value={value.watts} onChange={(v)=>setValue({...value,watts:v})}/></Field><Field label="每日使用小時"><Input type="number" min="0" step="0.1" value={value.hoursPerDay} onChange={(v)=>setValue({...value,hoursPerDay:v})}/></Field><Field label="優先級"><select value={value.priority} onChange={(e)=>setValue({...value,priority:e.target.value})}>{devicePriorities.map((v)=><option key={v} value={v}>{energyLabels[v]}</option>)}</select></Field><Check label="生存必要" checked={value.essential} onChange={(v)=>setValue({...value,essential:v})}/></div><Field label="備註"><textarea rows="2" value={value.notes} onChange={(e)=>setValue({...value,notes:e.target.value})}/></Field><FormActions cancel={cancel}/></form> }
function PowerForm({ value, setValue, save, cancel }) { return <form className="energy-form" onSubmit={save}><div className="energy-form-grid"><Field label="名稱"><Input value={value.name} onChange={(v)=>setValue({...value,name:v})}/></Field><Field label="類型"><select value={value.type} onChange={(e)=>setValue({...value,type:e.target.value})}>{powerSourceTypes.map((v)=><option key={v} value={v}>{energyLabels[v]}</option>)}</select></Field><Field label="容量 Wh"><Input type="number" min="0" value={value.capacityWh} onChange={(v)=>setValue({...value,capacityWh:v})}/></Field><Field label="可用百分比"><Input type="number" min="0" max="100" value={value.usablePercent} onChange={(v)=>setValue({...value,usablePercent:v})}/></Field><Field label="最大輸出 W"><Input type="number" min="0" value={value.maxOutputWatts} onChange={(v)=>setValue({...value,maxOutputWatts:v})}/></Field><Check label="可充電" checked={value.rechargeable} onChange={(v)=>setValue({...value,rechargeable:v})}/><Check label="依賴市電" checked={value.dependsOnGrid} onChange={(v)=>setValue({...value,dependsOnGrid:v})}/><Check label="可太陽能充電" checked={value.solarRecharge} onChange={(v)=>setValue({...value,solarRecharge:v})}/></div><Field label="備註"><textarea rows="2" value={value.notes} onChange={(e)=>setValue({...value,notes:e.target.value})}/></Field><FormActions cancel={cancel}/></form> }
function FuelForm({ value, setValue, save, cancel }) { return <form className="energy-form" onSubmit={save}><div className="energy-form-grid"><Field label="名稱"><Input value={value.name} onChange={(v)=>setValue({...value,name:v})}/></Field><Field label="類型"><select value={value.type} onChange={(e)=>setValue({...value,type:e.target.value})}>{fuelSourceTypes.map((v)=><option key={v} value={v}>{energyLabels[v]}</option>)}</select></Field><Field label="數量"><Input type="number" min="0" step="0.1" value={value.amount} onChange={(v)=>setValue({...value,amount:v})}/></Field><Field label="單位"><Input value={value.unit} onChange={(v)=>setValue({...value,unit:v})}/></Field><Field label="每單位可烹調次數"><Input type="number" min="0" step="0.1" value={value.usesPerUnit} onChange={(v)=>setValue({...value,usesPerUnit:v})}/></Field><Check label="適合室內安全使用" checked={value.safeIndoorUse} onChange={(v)=>setValue({...value,safeIndoorUse:v})}/></div><Field label="備註"><textarea rows="2" value={value.notes} onChange={(e)=>setValue({...value,notes:e.target.value})}/></Field><FormActions cancel={cancel}/></form> }
function PlanForm({ value, setValue, save, cancel }) { return <form className="energy-form" onSubmit={save}><div className="energy-form-grid"><Field label="名稱"><Input value={value.name} onChange={(v)=>setValue({...value,name:v})}/></Field>{[['durationDays','天數'],['lightingWhPerDay','照明 Wh / 日'],['communicationWhPerDay','通訊 Wh / 日'],['medicalWhPerDay','醫療 Wh / 日'],['refrigerationWhPerDay','冷藏 Wh / 日'],['otherWhPerDay','其他 Wh / 日'],['cookingUsesPerDay','烹調次數 / 日']].map(([key,label])=><Field key={key} label={label}><Input type="number" min="0" step="0.1" value={value[key]} onChange={(v)=>setValue({...value,[key]:v})}/></Field>)}</div><Field label="備註"><textarea rows="2" value={value.notes} onChange={(e)=>setValue({...value,notes:e.target.value})}/></Field><FormActions cancel={cancel}/></form> }
function FormActions({ cancel }) { return <div className="mt-3 flex gap-2"><button className="btn-primary">儲存</button><button type="button" className="btn-secondary" onClick={cancel}>取消</button></div> }
function EditButtons({ edit, remove, label }) { return <div className="flex"><button className="p-2" aria-label={`編輯${label}`} onClick={edit}><Pencil size={17}/></button><button className="p-2 text-[#8b2f25]" aria-label={`刪除${label}`} onClick={remove}><Trash2 size={17}/></button></div> }

export default function EnergySystem({ setPage }) {
  const [data,setData]=useState(loadEnergySystemData)
  const [deviceForm,setDeviceForm]=useState(null),[powerForm,setPowerForm]=useState(null),[fuelForm,setFuelForm]=useState(null),[planForm,setPlanForm]=useState(null)
  useEffect(()=>{saveEnergySystemData(data)},[data])
  const summary=useMemo(()=>getEnergySystemSummary(data),[data])
  const recommendations=[...new Set(summary.recommendations)]
  const update=(key,value)=>setData((current)=>({...current,[key]:value}))
  const saveItem=(event,key,form,setForm)=>{event.preventDefault();if(!form.name.trim())return;const items=Array.isArray(data[key])?data[key]:[];update(key,form.id?items.map((item)=>item.id===form.id?form:item):[{...form,id:uid()},...items]);setForm(null)}
  const removeItem=(key,id,name)=>{if(confirm(`確定刪除「${name}」？`))update(key,(data[key]||[]).filter((item)=>item.id!==id))}
  const profile=data.usageProfiles?.[data.currentProfile]||createDefaultEnergySystem().usageProfiles.blackout
  const updateProfile=(key,value)=>update('usageProfiles',{...data.usageProfiles,[data.currentProfile]:{...profile,[key]:value}})
  return <div className="energy-system space-y-5 pb-32"><button className="btn-secondary" onClick={()=>setPage('tools')}><ArrowLeft size={16} className="inline"/> 返回工具中心</button>
    <section className="muji-card energy-summary-card"><p className="muji-kicker">Energy System 1.0</p><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-2xl font-black text-bark">家庭能源系統</h1><p className="mt-1 text-sm">停電電力、通訊、照明與烹調續航。</p></div><div className="energy-score-card"><span>Energy Score</span><strong>{summary.score}</strong><small>{summary.status}</small></div></div><div className="metric-strip mt-3"><Metric label="狀態" value={summary.status}/><Metric label="必要設備支撐" value={`${fmt(summary.days.essentialElectricDays)} 天`}/><Metric label="烹調支撐" value={`${fmt(summary.days.cookingDays)} 天`}/><Metric label="可用電量" value={`${fmt(summary.totals.usablePowerWh)} Wh`}/></div><p className="mt-3 rounded-xl bg-white/55 p-3 text-sm font-bold">優先建議：{recommendations[0]}</p><div className="mt-3 rounded-xl border border-soil/15 bg-white/55 p-3"><div className="energy-form-grid"><Field label="用能模式"><select value={data.currentProfile} onChange={(e)=>update('currentProfile',e.target.value)}>{Object.keys(profileLabels).map((key)=><option key={key} value={key}>{profileLabels[key]}</option>)}</select></Field>{[['lightingHours','照明時數'],['communicationHours','通訊時數'],['medicalHours','醫療設備時數'],['cookingUsesPerDay','烹調次數 / 日']].map(([key,label])=><Field key={key} label={label}><Input type="number" min="0" step="0.1" value={profile[key]} onChange={(v)=>updateProfile(key,v)}/></Field>)}</div></div></section>

    <CollapsibleSection title="管理用電設備" subtitle={`${data.devices.length} 項設備`}><div className="flex items-center justify-between gap-3"><Title icon={Lightbulb}>用電設備管理</Title><button className="btn-secondary" onClick={()=>setDeviceForm({...emptyDevice})}><Plus size={16} className="inline"/> 新增設備</button></div>{deviceForm&&<DeviceForm value={deviceForm} setValue={setDeviceForm} save={(e)=>saveItem(e,'devices',deviceForm,setDeviceForm)} cancel={()=>setDeviceForm(null)}/>}<div className="energy-card-grid">{data.devices.map((item)=><article key={item.id} className="energy-device-card"><div className="flex justify-between gap-2"><div><h3>{item.name}</h3><p>{energyLabels[item.category]} · {energyLabels[item.priority]}</p></div><EditButtons label="用電設備" edit={()=>setDeviceForm({...item})} remove={()=>removeItem('devices',item.id,item.name)}/></div><strong>{fmt(safe(item.watts)*safe(item.hoursPerDay))} Wh / 日</strong><small>{item.essential?'生存必要':'非必要'} · {fmt(item.watts)} W × {fmt(item.hoursPerDay)} h</small></article>)}</div>{!data.devices.length&&<Empty/>}</CollapsibleSection>

    <CollapsibleSection title="管理供電來源" subtitle={`${data.powerSources.length} 個來源`}><div className="flex items-center justify-between gap-3"><Title icon={Battery}>供電來源管理</Title><button className="btn-secondary" onClick={()=>setPowerForm({...emptyPower})}><Plus size={16} className="inline"/> 新增來源</button></div>{powerForm&&<PowerForm value={powerForm} setValue={setPowerForm} save={(e)=>saveItem(e,'powerSources',powerForm,setPowerForm)} cancel={()=>setPowerForm(null)}/>}<div className="energy-card-grid">{data.powerSources.map((item)=><article key={item.id} className="energy-source-card"><div className="flex justify-between gap-2"><div><h3>{item.name}</h3><p>{energyLabels[item.type]}</p></div><EditButtons label="供電來源" edit={()=>setPowerForm({...item})} remove={()=>removeItem('powerSources',item.id,item.name)}/></div><strong>{fmt(safe(item.capacityWh)*Math.min(100,safe(item.usablePercent))/100)} Wh 可用</strong><small>最大輸出 {fmt(item.maxOutputWatts)} W · {item.dependsOnGrid?'依賴市電':'可離網'}</small></article>)}</div>{!data.powerSources.length&&<Empty/>}</CollapsibleSection>

    <CollapsibleSection title="管理燃料與烹調能源" subtitle={`${data.fuelSources.length} 個來源`}><div className="flex items-center justify-between gap-3"><Title icon={Fuel}>燃料與烹調能源</Title><button className="btn-secondary" onClick={()=>setFuelForm({...emptyFuel})}><Plus size={16} className="inline"/> 新增燃料</button></div>{fuelForm&&<FuelForm value={fuelForm} setValue={setFuelForm} save={(e)=>saveItem(e,'fuelSources',fuelForm,setFuelForm)} cancel={()=>setFuelForm(null)}/>}<div className="energy-card-grid">{data.fuelSources.map((item)=><article key={item.id} className="energy-fuel-card"><div className="flex justify-between gap-2"><div><h3>{item.name}</h3><p>{energyLabels[item.type]}</p></div><EditButtons label="燃料來源" edit={()=>setFuelForm({...item})} remove={()=>removeItem('fuelSources',item.id,item.name)}/></div><strong>{fmt(safe(item.amount)*safe(item.usesPerUnit))} 次烹調</strong><small>{fmt(item.amount)} {item.unit} · {item.safeIndoorUse?'標記可室內使用':'不可假設可室內使用'}</small></article>)}</div>{!data.fuelSources.length&&<Empty/>}</CollapsibleSection>

    <CollapsibleSection title="管理停電分配方案" subtitle={`${data.energyPlans.length} 個方案`}><div className="flex items-center justify-between gap-3"><Title icon={ClipboardList}>停電能源分配方案</Title><button className="btn-secondary" onClick={()=>setPlanForm({...emptyPlan})}><Plus size={16} className="inline"/> 新增方案</button></div>{planForm&&<PlanForm value={planForm} setValue={setPlanForm} save={(e)=>saveItem(e,'energyPlans',planForm,setPlanForm)} cancel={()=>setPlanForm(null)}/>}<div className="energy-card-grid">{data.energyPlans.map((item)=>{const result=evaluateEnergyPlan(item,data);return <article key={item.id} className="energy-plan-card"><div className="flex justify-between gap-2"><div><h3>{item.name}</h3><p>{fmt(item.durationDays)} 天方案</p></div><EditButtons label="能源方案" edit={()=>setPlanForm({...item})} remove={()=>removeItem('energyPlans',item.id,item.name)}/></div><strong>{fmt(result.totalWh)} Wh · {result.enough?'足夠':'不足'}</strong><small>電力缺口 {fmt(result.electricGap)} Wh · 烹調缺口 {fmt(result.cookingGap)} 次</small></article>})}</div>{!data.energyPlans.length&&<Empty/>}</CollapsibleSection>

    <section className="muji-card compact-card"><Title icon={Zap}>能源改善建議</Title><ol className="dense-list mt-3">{recommendations.slice(0,5).map((item,index)=><li key={item} className="rounded-xl border border-soil/15 bg-white/60 p-2 text-sm"><strong className="mr-2 text-[#8b2f25]">{index+1}.</strong>{item}</li>)}</ol></section>
    <section className="muji-card compact-card bg-[#f2dfd4]"><p className="font-black">能源安全</p><p className="mt-1 text-sm">燃料與燃燒設備可能造成一氧化碳中毒、火災或缺氧；依產品規範操作，勿在不通風室內使用。</p></section>
  </div>
}

function Empty(){return <p className="mt-4 rounded-2xl border border-dashed border-soil/25 p-5 text-center text-soil/60">尚無資料</p>}
