import React,{useEffect,useMemo,useState}from'react'
import{ArrowLeft,HeartPulse,Pencil,Plus,ShieldCheck,Trash2}from'lucide-react'
import{medicalModes,medicalTypeLabels}from'../data/medicalDefaults.js'
import{evaluateCarePlan}from'../utils/medicalCalculations.js'
import{getMedicalSystemSummary,loadMedicalSystemData,saveMedicalSystemData}from'../utils/medicalStorage.js'
const fmt=(value)=>Number.isFinite(Number(value))?Number(Number(value).toFixed(1)).toString():'0'
const uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`
const configs={
 firstAidItems:{title:'急救用品',types:['bandage','gauze','tape','antiseptic','saline','gloves','scissors','thermometer','splint','burnCare','coldPack','other'],fields:[['quantity','數量','number'],['unit','單位'],['usesPerUnit','每單位可用次數','number'],['expiresAt','有效期限','date']],checks:[['sterile','無菌']]},
 medicines:{title:'常備藥與症狀處理',types:['painFever','allergy','gastrointestinal','coldFlu','electrolyte','chronic','topical','eyeEar','other'],fields:[['quantity','數量','number'],['unit','單位'],['dailyDoseEstimate','每日用量估算','number'],['expiresAt','有效期限','date']],checks:[['forChildren','兒童適用'],['forPets','寵物適用'],['prescription','處方藥']]},
 chronicNeeds:{title:'慢性病與特殊需求',nameField:'personLabel',fields:[['condition','狀況'],['requiredItem','必要用品／藥物'],['dailyNeed','每日需求','number'],['availableDays','現有天數','number']],checks:[['critical','關鍵需求']]},
 petMedicalItems:{title:'寵物醫療用品',types:['woundCare','medication','syringe','eyeEar','digestive','chronic','restraint','other'],fields:[['species','物種'],['quantity','數量','number'],['unit','單位'],['dailyUseEstimate','每日用量估算','number'],['expiresAt','有效期限','date']]},
 emergencyContacts:{title:'緊急聯絡人',types:['hospital','clinic','pharmacy','vet','family','neighbor','emergency','other'],typeField:'role',fields:[['phone','電話'],['location','地點']],checks:[['available24h','24 小時可聯絡']]},
 carePlans:{title:'醫療照護方案',plan:true,fields:[['durationDays','方案天數','number'],['woundCareUsesPerDay','每日傷口處理次數','number'],['medicationDaysRequired','所需用藥天數','number'],['petCareUsesPerDay','每日寵物照護次數','number']],checks:[['chronicCareCovered','涵蓋慢性照護']]}
}
const empty=(key)=>{const config=configs[key];return{id:'',[config.nameField||'name']:'',type:config.types?.[0]||'',role:config.typeField==='role'?config.types[0]:'',notes:'',...Object.fromEntries(config.fields.map(([field,,kind])=>[field,kind==='number'?0:''])),...Object.fromEntries((config.checks||[]).map(([field])=>[field,false]))}}
export default function MedicalSystem({setPage}){const[data,setData]=useState(loadMedicalSystemData),[editing,setEditing]=useState({key:'',item:null});useEffect(()=>{saveMedicalSystemData(data)},[data]);const summary=useMemo(()=>getMedicalSystemSummary(data),[data]);const recommendations=[...new Set(summary.recommendations)].slice(0,5);const update=(key,value)=>setData((current)=>({...current,[key]:value}));const nested=(group,key,value)=>update(group,{...data[group],[key]:value});const begin=(key,item)=>setEditing({key,item:item?{...item}:empty(key)});const save=(event)=>{event.preventDefault();const{key,item}=editing,config=configs[key],name=item[config.nameField||'name'];if(!String(name).trim())return;update(key,item.id?data[key].map((entry)=>entry.id===item.id?item:entry):[{...item,id:uid()},...data[key]]);setEditing({key:'',item:null})};const remove=(key,item)=>{const name=item.name||item.personLabel;if(confirm(`確定刪除「${name}」？`))update(key,data[key].filter((entry)=>entry.id!==item.id))};return <div className="medical-system space-y-5 pb-32"><button className="btn-secondary" onClick={()=>setPage('tools')}><ArrowLeft size={16} className="inline"/> 返回工具中心</button>
<section className="muji-card medical-summary-card"><p className="muji-kicker">Medical System 1.0</p><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-2xl font-black text-bark">家庭醫療與急救系統</h1><p className="description mt-1">管理家庭與寵物的災害急救、用藥與特殊照護準備。</p></div><div className="medical-score-card"><span>Medical Score</span><strong>{summary.score}</strong><small>{summary.status}</small></div></div><div className="metric-strip mt-3"><Metric label="家庭人數" value={`${fmt(summary.totals.householdSize)} 人`}/><Metric label="急救支撐" value={`${fmt(summary.days.firstAidDays)} 天`}/><Metric label="整體醫療支撐" value={`${fmt(summary.days.overallDays)} 天`}/><Metric label="醫療模式" value={medicalModes[data.medicalMode]}/></div><p className="recommendation mt-3">最高優先建議：{recommendations[0]||'持續輪替用品並演練照護方案。'}</p></section>
<section className="muji-card"><Title>醫療總覽</Title><div className="mt-3 grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="急救支撐" value={`${fmt(summary.days.firstAidDays)} 天`}/><Metric label="常備藥支撐" value={`${fmt(summary.days.medicineDays)} 天`}/><Metric label="慢性需求支撐" value={data.chronicNeeds.length?`${fmt(summary.days.chronicDays)} 天`:'未設定'}/><Metric label="寵物醫療支撐" value={data.household.pets>0?`${fmt(summary.days.petMedicalDays)} 天`:'無需求'}/></div></section>
<section className="muji-card"><Title>家庭與醫療設定</Title><div className="medical-form-grid mt-3"><Field label="醫療模式"><select value={data.medicalMode} onChange={(e)=>update('medicalMode',e.target.value)}>{Object.entries(medicalModes).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></Field>{[['adults','成人'],['children','兒童'],['seniors','高齡者'],['specialNeeds','特殊需求者'],['pets','寵物數']].map(([key,label])=><Field key={key} label={label}><Num value={data.household[key]} onChange={(value)=>nested('household',key,value)}/></Field>)}{[['woundCareUsesPerPersonPerDay','每人每日傷口處理'],['medicationBufferDays','慢性用藥緩衝天數'],['petCareUsesPerPetPerDay','每隻寵物每日醫療耗材']].map(([key,label])=><Field key={key} label={label}><Num value={data.settings[key]} onChange={(value)=>nested('settings',key,value)}/></Field>)}</div></section>
{Object.entries(configs).map(([key,config])=><section key={key} className="muji-card"><div className="flex items-center justify-between gap-3"><Title>{config.title}</Title><button className="btn-secondary" onClick={()=>begin(key)}><Plus size={16} className="inline"/> 新增</button></div>{editing.key===key&&<Editor config={config} item={editing.item} setItem={(item)=>setEditing({key,item})} save={save} cancel={()=>setEditing({key:'',item:null})}/>}<div className="medical-card-grid">{data[key].map((item)=><article key={item.id} className={config.plan?'medical-plan-card':'medical-item-card'}><div className="flex justify-between gap-3"><div><h3>{item.name||item.personLabel}</h3>{(item.type||item.role)&&<p>{medicalTypeLabels[item.type||item.role]||item.type||item.role}</p>}</div><div className="shrink-0"><button aria-label={`編輯${item.name||item.personLabel}`} className="p-2" onClick={()=>begin(key,item)}><Pencil size={16}/></button><button aria-label={`刪除${item.name||item.personLabel}`} className="p-2 text-[#8b2f25]" onClick={()=>remove(key,item)}><Trash2 size={16}/></button></div></div>{config.plan?<Plan item={item} summary={summary}/>:<p className="card-details mt-2">{config.fields.filter(([,label])=>label!=='單位').slice(0,3).map(([field,label])=>`${label} ${item[field]||'未設定'}`).join(' · ')}</p>}{item.notes&&<small>{item.notes}</small>}</article>)}</div>{!data[key].length&&<p className="empty-state mt-3">尚未建立資料。</p>}</section>)}
<section className="muji-card compact-card"><Title>醫療系統改善建議</Title><ol className="dense-list mt-3">{recommendations.map((item,index)=><li key={item} className="recommendation"><strong className="mr-2 text-[#8b2f25]">{index+1}.</strong>{item}</li>)}</ol></section><section className="muji-card compact-card bg-[#f2dfd4]"><div className="flex gap-3"><ShieldCheck size={20} className="shrink-0"/><p>醫療系統為家庭韌性規劃工具，不能取代醫師、藥師或獸醫診斷。藥物使用、兒童用藥、慢性病用藥與寵物用藥需依專業人員指示。若出現嚴重外傷、呼吸困難、意識異常、劇烈疼痛或中毒疑慮，請立即尋求緊急醫療協助。</p></div></section></div>}
function Editor({config,item,setItem,save,cancel}){const nameField=config.nameField||'name',typeField=config.typeField||'type';return <form className="medical-form" onSubmit={save}><div className="medical-form-grid"><Field label={nameField==='personLabel'?'成員標籤':'名稱'}><input required value={item[nameField]} onChange={(e)=>setItem({...item,[nameField]:e.target.value})}/></Field>{config.types&&<Field label={typeField==='role'?'角色':'類型'}><select value={item[typeField]} onChange={(e)=>setItem({...item,[typeField]:e.target.value})}>{config.types.map((type)=><option key={type} value={type}>{medicalTypeLabels[type]||type}</option>)}</select></Field>}{config.fields.map(([field,label,kind])=><Field key={field} label={label}>{kind==='number'?<Num value={item[field]} onChange={(value)=>setItem({...item,[field]:value})}/>:<input type={kind||'text'} value={item[field]} onChange={(e)=>setItem({...item,[field]:e.target.value})}/>}</Field>)}</div><div className="mt-3 flex flex-wrap gap-3">{(config.checks||[]).map(([field,label])=><label key={field} className="check-label"><input type="checkbox" checked={Boolean(item[field])} onChange={(e)=>setItem({...item,[field]:e.target.checked})}/>{label}</label>)}</div><Field label="備註"><textarea rows="2" value={item.notes} onChange={(e)=>setItem({...item,notes:e.target.value})}/></Field><div className="action-row mt-3"><button className="btn-primary">儲存</button><button type="button" className="btn-secondary" onClick={cancel}>取消</button></div></form>}
function Plan({item,summary}){const result=evaluateCarePlan(item,summary);return <p className={`mt-2 font-black ${result.enough?'text-[#24483a]':'text-[#8b2f25]'}`}>{fmt(result.durationDays)} 天方案 · {result.status}</p>};function Field({label,children}){return <label className="field-label"><span>{label}</span>{children}</label>};function Num({value,onChange}){return <input type="number" min="0" step="0.1" value={value} onChange={(e)=>onChange(e.target.value)}/>};function Title({children}){return <div className="muji-section-title"><HeartPulse size={18}/><span>{children}</span></div>};function Metric({label,value}){return <div className="metric-card"><p className="metric-label">{label}</p><strong className="metric-value">{value}</strong></div>}
