export function sanitizeNumber(value){const parsed=Number(value);return Number.isFinite(parsed)&&parsed>0?parsed:0}
const list=(value)=>Array.isArray(value)?value:[],pct=(points,max)=>Math.round(Math.min(100,points/max*100))
export function calculateContactCoverage(contacts=[]){const items=list(contacts);let p=0;if(items.some((i)=>['critical','high'].includes(i?.priority)))p+=2;if(items.some((i)=>i?.hasPaperCopy))p++;if(items.some((i)=>i?.alternatePhone||i?.address))p++;for(const role of['family','neighbor','medical','vet'])if(items.some((i)=>i?.role===role))p++;return pct(p,8)}
export function calculateDeviceReadiness(devices=[]){const items=list(devices);let p=0;if(items.some((i)=>i?.type==='phone'))p++;if(items.some((i)=>['powerCable','powerAdapter'].includes(i?.type)))p++;if(items.some((i)=>['radio','walkieTalkie','hamRadio','whistle','signalLight'].includes(i?.type)))p+=2;if(items.some((i)=>i?.hasBackupPower))p++;if(items.some((i)=>i?.offlineCapable))p++;return pct(p,6)}
export function calculateOfflineInfoReadiness(sources=[],devices=[]){const items=list(sources);let p=0;if(items.some((i)=>i?.type==='offlineMap')||list(devices).some((i)=>i?.type==='paperMap'))p++;if(items.some((i)=>i?.type==='printedGuide'))p++;if(items.some((i)=>i?.trusted))p++;if(items.some((i)=>i?.type==='radioBroadcast'&&i?.frequency))p++;if(items.some((i)=>i?.type==='governmentWebsite'))p++;return pct(p,5)}
export function calculateMeetingPointReadiness(points=[]){const items=list(points);let p=0;if(items.some((i)=>i?.type==='home'))p++;if(items.some((i)=>i?.type==='nearby'))p++;if(items.some((i)=>!['home','nearby'].includes(i?.type)))p++;if(items.some((i)=>i?.petFriendly))p++;if(items.some((i)=>i?.accessibleForSeniors))p++;return pct(p,5)}
export function calculateMessagePlanReadiness(plans=[]){const items=list(plans);let p=0;if(items.length)p++;if(items.some((i)=>i?.primaryMethod&&i?.backupMethod))p++;if(items.some((i)=>i?.outOfAreaContact))p++;if(items.some((i)=>i?.meetingPointId))p++;if(items.some((i)=>i?.includesPets))p++;return pct(p,5)}
export function calculateDocumentReadiness(docs=[]){const items=list(docs);let p=0;for(const type of['contactList','medicalInfo','petInfo','map'])if(items.some((i)=>i?.type===type&&(i?.hasPrintedCopy||i?.hasOfflineDigitalCopy)))p++;if(items.some((i)=>i?.hasOfflineDigitalCopy))p++;return pct(p,5)}
export function calculateCommunicationScore(readiness={}){return Math.round((sanitizeNumber(readiness.contactCoverage)*25+sanitizeNumber(readiness.deviceReadiness)*20+sanitizeNumber(readiness.offlineInfoReadiness)*15+sanitizeNumber(readiness.meetingPointReadiness)*15+sanitizeNumber(readiness.messagePlanReadiness)*15+sanitizeNumber(readiness.documentReadiness)*10)/100)}
export function getCommunicationStatus(score){const v=Math.min(100,sanitizeNumber(score));if(v<30)return'Critical';if(v<50)return'Fragile';if(v<70)return'Prepared';if(v<85)return'Resilient';return'Fortified'}
export function generateCommunicationRecommendations(data={}){const contacts=list(data.contacts),devices=list(data.devices),sources=list(data.informationSources),points=list(data.meetingPoints),plans=list(data.messagePlans),docs=list(data.offlineDocuments),recs=[];if(!contacts.length)recs.push('沒有緊急聯絡人：建立家人、鄰居與專業支援清單。');if(!contacts.some((i)=>i?.hasPaperCopy)&&!docs.some((i)=>i?.type==='contactList'&&i?.hasPrintedCopy))recs.push('沒有紙本聯絡清單：準備至少兩份並放在固定位置。');if(!contacts.some((i)=>['neighbor','family','friend'].includes(i?.role)))recs.push('沒有鄰居或親友聯絡人：建立近距離互助聯絡。');if(!contacts.some((i)=>['medical','vet'].includes(i?.role)))recs.push('沒有醫療或獸醫聯絡人：記錄平日與緊急資訊。');if(!devices.some((i)=>i?.type==='radio')&&!sources.some((i)=>i?.offlineAvailable))recs.push('沒有收音機或離線資訊來源：建立斷網資訊管道。');if(!devices.some((i)=>['radio','walkieTalkie','hamRadio','whistle','signalLight'].includes(i?.type)))recs.push('沒有不依賴網路的通訊方式：增加收音機、對講機或信號工具。');if(!points.length)recs.push('沒有集合地點：建立家中、附近與外部備援地點。');if(!plans.some((i)=>i?.outOfAreaContact))recs.push('沒有外地聯絡人：指定災區外的訊息中繼人。');if(!plans.length)recs.push('沒有家庭報平安計畫：建立主要、備援方法與集合點。');if(!sources.some((i)=>i?.type==='offlineMap')&&!docs.some((i)=>i?.type==='map'))recs.push('沒有離線地圖：保留紙本或離線數位地圖。');if(sanitizeNumber(data.household?.pets)>0&&!docs.some((i)=>i?.type==='petInfo')&&!plans.some((i)=>i?.includesPets))recs.push('沒有寵物資訊備份：記錄聯絡、醫療與集合安排。');if(sanitizeNumber(data.household?.seniors)+sanitizeNumber(data.household?.specialNeeds)>0&&!points.some((i)=>i?.accessibleForSeniors))recs.push('沒有高齡者或特殊需求者通訊安排：建立可及集合點與紙本流程。');return[...new Set(recs)]}
export function evaluateCommunicationPlan(plan={},summary={}){const primary=Boolean(plan.primaryMethod),backup=Boolean(plan.backupMethod),out=Boolean(plan.outOfAreaContact),meeting=Boolean(plan.meetingPointId),pets=sanitizeNumber(summary.data?.household?.pets)<=0||Boolean(plan.includesPets),passed=[primary,backup,out,meeting,pets].filter(Boolean).length;return{passed,total:5,status:passed===5?'通過':passed>=3?'部分不足':'失敗',ready:passed===5}}
