export function sanitizeNumber(value){const parsed=Number(value);return Number.isFinite(parsed)&&parsed>0?parsed:0}
const list=(value)=>Array.isArray(value)?value:[]
const sumItems=(items,fn)=>list(items).reduce((sum,item)=>sum+fn(item),0)
export function calculateHouseholdCaloriesPerDay(household={},settings={},mode='emergency'){const base=sanitizeNumber(household.adults)*sanitizeNumber(settings.adultCaloriesPerDay)+sanitizeNumber(household.children)*sanitizeNumber(settings.childCaloriesPerDay)+sanitizeNumber(household.seniors)*sanitizeNumber(settings.seniorCaloriesPerDay)+sanitizeNumber(household.specialNeeds)*sanitizeNumber(settings.specialNeedsCaloriesPerDay);const multiplier={emergency:sanitizeNumber(settings.emergencyCaloriesMultiplier),conservation:sanitizeNumber(settings.conservationCaloriesMultiplier),normal:sanitizeNumber(settings.normalCaloriesMultiplier)}[mode]||1;return base*multiplier}
export function calculateFoodServings(items=[]){return sumItems(items,(item)=>sanitizeNumber(item.quantity)*sanitizeNumber(item.servingsPerUnit))}
export function calculateFoodCalories(items=[]){return sumItems(items,(item)=>sanitizeNumber(item.quantity)*sanitizeNumber(item.servingsPerUnit)*sanitizeNumber(item.caloriesPerServing))}
export function calculateReadyToEatCalories(items=[]){return calculateFoodCalories(list(items).filter((item)=>item?.readyToEat))}
export function calculateCookingRequiredCalories(items=[]){return calculateFoodCalories(list(items).filter((item)=>item?.requiresCooking||item?.requiresEnergy))}
export function calculateWaterRequiredForFood(items=[]){return sumItems(list(items).filter((item)=>item?.requiresWater),(item)=>sanitizeNumber(item.quantity)*sanitizeNumber(item.servingsPerUnit)*sanitizeNumber(item.waterLitersPerServing))}
export function calculateFoodSupportDays(totalCalories,dailyNeed){return sanitizeNumber(dailyNeed)>0?sanitizeNumber(totalCalories)/sanitizeNumber(dailyNeed):0}
export function calculatePetFoodSupportDays(items=[],household={},settings={}){const demand=sanitizeNumber(household.pets)*sanitizeNumber(settings.petServingsPerPetPerDay);const servings=sumItems(items,(item)=>sanitizeNumber(item.quantity)*sanitizeNumber(item.servingsPerUnit));return demand>0?servings/demand:0}
export function calculateOverallFoodDays(days={},hasPets=false){const values=[days.foodDays,hasPets?days.petFoodDays:null].filter((value)=>value!==null).map(sanitizeNumber);return values.length?Math.min(...values):0}
export function getFoodStatus(score){const value=Math.min(100,sanitizeNumber(score));if(value<30)return'Critical';if(value<50)return'Fragile';if(value<70)return'Prepared';if(value<85)return'Resilient';return'Fortified'}
const expiry=(value)=>{if(!value)return'missing';const time=new Date(value).getTime();if(!Number.isFinite(time))return'missing';return time<=Date.now()+30*86400000?'expiring':'valid'}
export function calculateFoodScore(data={},summary={}){const items=list(data.foodItems),pets=sanitizeNumber(data.household?.pets);let score=items.length?Math.min(30,10+sanitizeNumber(summary.days?.foodDays)*4):0;score+=sanitizeNumber(summary.days?.readyToEatDays)>=3?20:sanitizeNumber(summary.totals?.readyToEatCalories)>0?10:0;score+=items.some((item)=>!item?.requiresWater||sanitizeNumber(item?.waterLitersPerServing)<=.25)?10:0;score+=list(data.cookingPlans).length?10:0;score+=pets===0?10:list(data.petFoodItems).length?10:0;const dated=[...items,...list(data.petFoodItems)];if(dated.length&&dated.every((item)=>expiry(item.expiresAt)==='valid'))score+=10;score+=list(data.rationPlans).length?10:0;return Math.round(Math.min(100,score))}
export function generateFoodRecommendations(data={},summary={}){const items=list(data.foodItems),pets=sanitizeNumber(data.household?.pets),recs=[];if(!items.length)recs.push('沒有食物庫存：建立至少 72 小時的家庭食物熱量。');const days=sanitizeNumber(summary.days?.foodDays);if(days<1)recs.push('食物支撐低於 24 小時：立即補足可安全食用的食物。');else if(days<3)recs.push('食物支撐低於 72 小時：先建立三天最低熱量。');else if(days<7)recs.push('食物支撐低於 7 天：逐步建立補給中斷緩衝。');if(sanitizeNumber(summary.days?.readyToEatDays)<3)recs.push('免烹調食物不足：增加停電停水時可直接食用的品項。');if(items.length&&items.filter((item)=>item?.requiresWater).length>items.length/2)recs.push('大多數食物需要水：增加低用水或免加水食物。');if(items.length&&items.filter((item)=>item?.requiresEnergy).length>items.length/2)recs.push('大多數食物需要能源烹調：增加免烹調或低能源品項。');if(!list(data.cookingPlans).length)recs.push('沒有烹調方案：建立停電時可安全使用的方式。');if(pets>0&&!list(data.petFoodItems).length)recs.push('有寵物但沒有寵物食物：建立至少 72 小時寵物份數。');if(!list(data.rationPlans).length)recs.push('沒有配給方案：建立 72 小時與 7 天分配規則。');if([...items,...list(data.petFoodItems)].some((item)=>expiry(item.expiresAt)!=='valid'))recs.push('有即將過期或缺少效期的食物：建立輪替與補貨制度。');const special=sanitizeNumber(data.household?.children)+sanitizeNumber(data.household?.seniors)+sanitizeNumber(data.household?.specialNeeds);if(special>0&&!items.some((item)=>['babyFood','seniorFood','specialDiet'].includes(item?.type)))recs.push('缺少兒童、高齡者或特殊飲食需求食物。');return[...new Set(recs)]}
export function evaluateRationPlan(plan={},summary={}){const durationDays=sanitizeNumber(plan.durationDays),household=summary.data?.household||{},required=(sanitizeNumber(household.adults)*sanitizeNumber(plan.caloriesPerAdultPerDay)+sanitizeNumber(household.children)*sanitizeNumber(plan.caloriesPerChildPerDay)+sanitizeNumber(household.seniors)*sanitizeNumber(plan.caloriesPerSeniorPerDay)+sanitizeNumber(household.specialNeeds)*sanitizeNumber(plan.caloriesPerSpecialNeedsPerDay))*durationDays,petRequired=sanitizeNumber(household.pets)*sanitizeNumber(plan.petServingsPerPetPerDay)*durationDays,enough=sanitizeNumber(summary.totals?.totalCalories)>=required&&sanitizeNumber(summary.totals?.totalPetServings)>=petRequired;return{durationDays,requiredCalories:required,requiredPetServings:petRequired,enough,status:enough?'足夠':'不足'}}
