export function sanitizeNumber(value) { const parsed=Number(value); return Number.isFinite(parsed)&&parsed>0?parsed:0 }
const list=(value)=>Array.isArray(value)?value:[]
const factor=(mode)=>({emergency:0.7,conservation:0.85,normal:1}[mode]||0.7)
const minPositive=(values)=>{const safe=values.map(sanitizeNumber).filter((value)=>value>0);return safe.length?Math.min(...safe):0}
export function calculateHouseholdSize(household={}) { return ['adults','children','seniors','specialNeeds'].reduce((sum,key)=>sum+sanitizeNumber(household?.[key]),0) }
export function calculateFirstAidCapacity(items=[]) { return list(items).reduce((sum,item)=>sum+sanitizeNumber(item?.quantity)*(sanitizeNumber(item?.usesPerUnit)||1),0) }
export function calculateMedicineSupportDays(items=[]) { return minPositive(list(items).map((item)=>sanitizeNumber(item?.dailyDoseEstimate)>0?sanitizeNumber(item?.quantity)/sanitizeNumber(item?.dailyDoseEstimate):0)) }
export function calculateChronicSupportDays(needs=[]) { return minPositive(list(needs).map((item)=>item?.availableDays)) }
export function calculatePetMedicalSupportDays(items=[],household={},settings={},mode='emergency') { const demand=sanitizeNumber(household?.pets)*sanitizeNumber(settings?.petCareUsesPerPetPerDay)*factor(mode);const capacities=list(items).map((item)=>sanitizeNumber(item?.dailyUseEstimate)>0?sanitizeNumber(item?.quantity)/sanitizeNumber(item?.dailyUseEstimate):0);return demand>0?minPositive(capacities):0 }
export function calculateMedicalSupportDays(days={},options={}) { const values=[days.firstAidDays,days.medicineDays,options.hasChronic?days.chronicDays:null,options.hasPets?days.petMedicalDays:null].filter((value)=>value!==null).map(sanitizeNumber);return values.length?Math.min(...values):0 }
export function getMedicalStatus(score) { const value=Math.min(100,sanitizeNumber(score));if(value<30)return'Critical';if(value<50)return'Fragile';if(value<70)return'Prepared';if(value<85)return'Resilient';return'Fortified' }
const dateState=(value)=>{if(!value)return'missing';const time=new Date(value).getTime();if(!Number.isFinite(time))return'missing';return time<=Date.now()+30*86400000?'expiring':'valid'}
export function calculateMedicalScore(data={},days={}) { const first=list(data.firstAidItems),meds=list(data.medicines),chronic=list(data.chronicNeeds),pets=sanitizeNumber(data.household?.pets);let score=first.length?Math.min(25,10+sanitizeNumber(days.firstAidDays)*3):0;score+=meds.length?Math.min(20,8+sanitizeNumber(days.medicineDays)*2):0;score+=chronic.length?chronic.every((item)=>sanitizeNumber(item?.availableDays)>=7)?20:10:20;score+=pets===0?10:list(data.petMedicalItems).length?10:0;score+=list(data.emergencyContacts).some((item)=>['hospital','clinic','pharmacy','emergency'].includes(item?.role))?10:0;score+=list(data.carePlans).length?10:0;const dated=[...first,...meds,...list(data.petMedicalItems)];if(dated.length&&dated.every((item)=>dateState(item?.expiresAt)==='valid'))score+=5;return Math.round(Math.min(100,score)) }
export function generateMedicalRecommendations(data={},days={}) { const first=list(data.firstAidItems),meds=list(data.medicines),chronic=list(data.chronicNeeds),contacts=list(data.emergencyContacts),pets=sanitizeNumber(data.household?.pets);const recs=[];if(!first.length)recs.push('沒有急救用品：建立可處理常見外傷的基本急救包。');if(!first.some((item)=>['antiseptic','saline'].includes(item?.type)))recs.push('沒有消毒或生理食鹽水：補齊傷口清潔用品。');if(!first.some((item)=>item?.type==='gloves'))recs.push('沒有手套或防護用品：降低接觸血液與污染物的風險。');if(!meds.length)recs.push('沒有常備藥：依醫師或藥師建議建立家庭用藥清單。');if(chronic.some((item)=>item?.critical&&sanitizeNumber(item?.availableDays)<7))recs.push('慢性病藥物不足 7 天：優先依處方補足安全緩衝。');if(pets>0&&!list(data.petMedicalItems).length)recs.push('有寵物但沒有寵物醫療用品：建立基本照護與用藥清單。');if(!contacts.some((item)=>['hospital','clinic','pharmacy','emergency'].includes(item?.role)))recs.push('沒有緊急醫療聯絡人：記錄醫院、診所或緊急服務資訊。');if(pets>0&&!contacts.some((item)=>item?.role==='vet'))recs.push('沒有獸醫聯絡人：記錄平日與夜間可用的獸醫資訊。');if(!list(data.carePlans).length)recs.push('沒有醫療照護方案：建立 72 小時傷口、用藥與慢性照護分配。');const dated=[...first,...meds,...list(data.petMedicalItems)];if(dated.some((item)=>dateState(item?.expiresAt)!=='valid'))recs.push('有用品即將過期或缺少效期：建立每月效期檢查與輪替。');const special=sanitizeNumber(data.household?.children)+sanitizeNumber(data.household?.seniors)+sanitizeNumber(data.household?.specialNeeds);if(special>0&&!chronic.length&&!meds.some((item)=>item?.forChildren))recs.push('沒有兒童、高齡者或特殊需求者規劃：補上個別用藥與照護需求。');if(sanitizeNumber(days.overallDays)<3)recs.push('整體醫療支撐低於 72 小時：先補強最短的醫療能力。');return[...new Set(recs)] }
export function evaluateCarePlan(plan={},summary={}) { const durationDays=sanitizeNumber(plan?.durationDays);const enough=durationDays>0&&sanitizeNumber(summary?.days?.overallDays)>=durationDays;return{durationDays,required:{woundCareUses:sanitizeNumber(plan?.woundCareUsesPerDay)*durationDays,medicationDays:sanitizeNumber(plan?.medicationDaysRequired),petCareUses:sanitizeNumber(plan?.petCareUsesPerDay)*durationDays},chronicCareCovered:Boolean(plan?.chronicCareCovered),enough,status:enough?'足夠':'不足'} }
